clc;
clear all;
close all;

[ SumCapacity1,SelectedReceiveAntenna1,SelectedUser1,DataStreams1 ] = SuboptimalAlgorithm1(5,2, 1,5,20);
[ SumCapacity2,SelectedReceiveAntenna2,SelectedUser2,DataStreams2 ] = SuboptimalAlgorithm2( 5,2, 1,5,20);
disp(SumCapacity1);
disp(SumCapacity2);
[ SumCapacity1,SelectedReceiveAntenna1,SelectedUser1,DataStreams1 ] = SuboptimalAlgorithm1(5,2, 1,5,20);
[ SumCapacity2,SelectedReceiveAntenna2,SelectedUser2,DataStreams2 ] = SuboptimalAlgorithm2( 5,2, 1,5,20);
disp(SumCapacity1);
disp(SumCapacity2);
[ SumCapacity1,SelectedReceiveAntenna1,SelectedUser1,DataStreams1 ] = SuboptimalAlgorithm1(5,2, 1,5,20);
[ SumCapacity2,SelectedReceiveAntenna2,SelectedUser2,DataStreams2 ] = SuboptimalAlgorithm2( 5,2, 1,5,20);
disp(SumCapacity1);
disp(SumCapacity2);
[ SumCapacity1,SelectedReceiveAntenna1,SelectedUser1,DataStreams1 ] = SuboptimalAlgorithm1(5,2, 1,5,20);
[ SumCapacity2,SelectedReceiveAntenna2,SelectedUser2,DataStreams2 ] = SuboptimalAlgorithm2( 5,2, 1,5,20);
disp(SumCapacity1);
disp(SumCapacity2);
