clc;
clear all;
close all;

z=zeros(1,10);
y=zeros(1,10);
x=1:10;

[ SumCapacity1,SelectedReceiveAntenna1,SelectedUser1,DataStreams1 ] = SuboptimalAlgorithm1(5,2, 1,1,20);
[ SumCapacity2,SelectedReceiveAntenna2,SelectedUser2,DataStreams2 ] = SuboptimalAlgorithm2( 5,2, 1,1,20);
disp(SumCapacity1);
disp(SumCapacity2);
y(1)=SumCapacity1;
z(1)=SumCapacity2;
[ SumCapacity1,SelectedReceiveAntenna1,SelectedUser1,DataStreams1 ] = SuboptimalAlgorithm1(5,2, 1,2,20);
[ SumCapacity2,SelectedReceiveAntenna2,SelectedUser2,DataStreams2 ] = SuboptimalAlgorithm2( 5,2, 1,2,20);
disp(SumCapacity1);
disp(SumCapacity2);
y(2)=SumCapacity1;
z(2)=SumCapacity2;
[ SumCapacity1,SelectedReceiveAntenna1,SelectedUser1,DataStreams1 ] = SuboptimalAlgorithm1(5,2, 1,3,20);
[ SumCapacity2,SelectedReceiveAntenna2,SelectedUser2,DataStreams2 ] = SuboptimalAlgorithm2( 5,2, 1,3,20);
disp(SumCapacity1);
disp(SumCapacity2);
y(3)=SumCapacity1;
z(3)=SumCapacity2;
[ SumCapacity1,SelectedReceiveAntenna1,SelectedUser1,DataStreams1 ] = SuboptimalAlgorithm1(5,2, 1,4,20);
[ SumCapacity2,SelectedReceiveAntenna2,SelectedUser2,DataStreams2 ] = SuboptimalAlgorithm2( 5,2, 1,4,20);
disp(SumCapacity1);
disp(SumCapacity2);
y(4)=SumCapacity1;
z(4)=SumCapacity2;
[ SumCapacity1,SelectedReceiveAntenna1,SelectedUser1,DataStreams1 ] = SuboptimalAlgorithm1(5,2, 1,5,20);
[ SumCapacity2,SelectedReceiveAntenna2,SelectedUser2,DataStreams2 ] = SuboptimalAlgorithm2( 5,2, 1,5,20);
disp(SumCapacity1);
disp(SumCapacity2);
y(5)=SumCapacity1;
z(5)=SumCapacity2;
[ SumCapacity1,SelectedReceiveAntenna1,SelectedUser1,DataStreams1 ] = SuboptimalAlgorithm1(5,2, 1,6,20);
[ SumCapacity2,SelectedReceiveAntenna2,SelectedUser2,DataStreams2 ] = SuboptimalAlgorithm2( 5,2, 1,6,20);
disp(SumCapacity1);
disp(SumCapacity2);
y(6)=SumCapacity1;
z(6)=SumCapacity2;
[ SumCapacity1,SelectedReceiveAntenna1,SelectedUser1,DataStreams1 ] = SuboptimalAlgorithm1(5,2, 1,7,20);
[ SumCapacity2,SelectedReceiveAntenna2,SelectedUser2,DataStreams2 ] = SuboptimalAlgorithm2( 5,2, 1,7,20);
disp(SumCapacity1);
disp(SumCapacity2);
y(7)=SumCapacity1;
z(7)=SumCapacity2;
[ SumCapacity1,SelectedReceiveAntenna1,SelectedUser1,DataStreams1 ] = SuboptimalAlgorithm1(5,2, 1,8,20);
[ SumCapacity2,SelectedReceiveAntenna2,SelectedUser2,DataStreams2 ] = SuboptimalAlgorithm2( 5,2, 1,8,20);
disp(SumCapacity1);
disp(SumCapacity2);
y(8)=SumCapacity1;
z(8)=SumCapacity2;
[ SumCapacity1,SelectedReceiveAntenna1,SelectedUser1,DataStreams1 ] = SuboptimalAlgorithm1(5,2, 1,9,20);
[ SumCapacity2,SelectedReceiveAntenna2,SelectedUser2,DataStreams2 ] = SuboptimalAlgorithm2( 5,2, 1,9,20);
disp(SumCapacity1);
disp(SumCapacity2);
y(9)=SumCapacity1;
z(9)=SumCapacity2;
[ SumCapacity1,SelectedReceiveAntenna1,SelectedUser1,DataStreams1 ] = SuboptimalAlgorithm1(5,2, 1,16,20);
[ SumCapacity2,SelectedReceiveAntenna2,SelectedUser2,DataStreams2 ] = SuboptimalAlgorithm2( 5,2, 1,10,20);
disp(SumCapacity1);
disp(SumCapacity2);
y(10)=SumCapacity1;
z(10)=SumCapacity2;
figure(1)
plot(x,y)
figure(2)
plot(x,z)